[workspace]
resolver = "2"
members = ["crates/morse-core", "crates/morse-app"]

[workspace.package]
edition = "2021"
license = "Apache-2.0"

# Smaller, faster WASM / native release binaries.
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
